
version: '3.8'

services:
  pulsar:
    image: apachepulsar/pulsar:3.1.0
    command: bin/pulsar standalone
    ports:
      - "6650:6650"    # puerto para la app (protocolo binario)
      - "8080:8080"    # puerto del panel web (Admin API)
    environment:
      PULSAR_MEM: "-Xms256m -Xmx512m"
    volumes:
      - pulsar-data:/pulsar/data

volumes:
  pulsar-data:
